### ISSUE TITLE
Preserve user entries

### ISSUE THREAD

**Issue by bradfitz** [pwaller/goimports-update-ignore#1]
The `.goimportsignore` file supports comments. You could take advantage of this and preserve the user's explicit lines, putting your auto-generated entries in their own "section":

```
linux
foo/bar

# AUTO-GENERATED BY goimports-update-ignore
quux
a/b/c
# END-AUTO-GENERATED BY goimports-update-ignore
```

(with the user ones at top, for instance)

**Comment by pwaller** [comment]
I don't have the time to do this myself right now, but I'd be more than happy to see it implemented!

Pull requests welcomed.

**Comment by pwaller** [comment]
(Also @bradfitz, I'd be happy to see this functionality or similar ship in goimports if you thought it was appropriate).

**Comment by bradfitz** [comment]
Yeah, I might make goimports do this automatically if it finds a suitable large useless subtree. Figuring out the exact heuristics might be tricky.
